version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./config/jellyfin:/config
      - /mnt/wd2/arr/media:/media
    ports:
      - 8096:8096
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - LOG_LEVEL=debug
    volumes:
      - ./config/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./config/sonarr:/config
      - /mnt/wd2/arr/media/tv:/tv
      - /mnt/wd2/arr/downloads:/downloads
    ports:
      - 8991:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./config/radarr:/config
      - /mnt/wd2/arr/media/movies:/movies
      - /mnt/wd2/arr/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  bookshelf:
    image: ghcr.io/pennydreadful/bookshelf:softcover
    container_name: bookshelf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./config/bookshelf:/config
      - /mnt/wd2/arr/media/books:/books
      - /mnt/wd2/arr/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./config/jackett:/config
      - /mnt/wd2/arr/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  overseerr-bot:
    image: chimpanzeesweetrolls/overseerrrequestviatelegrambot:latest
    container_name: overseerr-bot
    environment:
      OVERSEERR_API_URL: "http://jellyseerr:5055/api/v1"
      OVERSEERR_API_KEY: "MTc3Mzg2NTY4MTQ4MGNiMzEyZjVlLTlmZWItNDYwYy05ODhmLWU5YzlmNzMyZjRmMw=="
      TELEGRAM_TOKEN: "8366447590:AAE5BDsgMUv16FghiuLVmQQQq7ybe_hXc7k"
      PASSWORD: "moothz_password" # Você pode alterar esta senha depois no Telegram
    volumes:
      - ./config/overseerr-bot:/app/data
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/wd2/arr/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
